import { Notice, TFile, normalizePath } from "obsidian";
import type LetterboxdPlugin from "./main";
import type { LetterboxdAccount } from "./types";

function buildWikiMarkdown(account: LetterboxdAccount, plugin: LetterboxdPlugin): string {
    const now = new Date().toISOString();
    const accName = account.name || account.username;
    const analyticsFolder = `${accName}/Analytics`;

    const commands = [
        { id: 'sync-diary', name: 'Sync Letterboxd diary', desc: 'Fetch diary entries and create or update diary notes. Runs RSS scraping and creates diary files.' },
        { id: 'import-csv', name: 'Import from CSV', desc: 'Import films/reviews from a Letterboxd CSV export. Use the folder picker and select the exported directory.' },
        { id: 'sync-films', name: 'Sync TMDB film data', desc: 'Enrich film notes using TMDB metadata (requires TMDB API token).' },
        { id: 'debug-check-tmdb-key', name: 'Debug: Check TMDB API Key', desc: 'Quickly check whether the TMDB API key is available (vault secrets preferred, settings fallback).' },
        { id: 'add-account', name: 'Add Letterboxd Account', desc: 'Add a new Letterboxd account to plugin settings (name, username, type).' },
        { id: 'switch-account', name: 'Switch Letterboxd Account', desc: 'Switch the active account used by commands.' },
        { id: 'remove-account', name: 'Remove Letterboxd Account', desc: 'Remove a configured account (with confirmation). Does not delete files.' },
        { id: 'list-accounts', name: 'List Letterboxd Accounts', desc: 'Show configured accounts and their last sync timestamps.' },
        { id: 'sync-active-account', name: 'Sync Active Account', desc: 'Run sync for the currently active account only.' },
        { id: 'sync-all-accounts', name: 'Sync All Accounts', desc: 'Run manual sync for all configured accounts.' },
        { id: 'sync-watchlist', name: 'Sync Letterboxd Watchlist', desc: 'Scrape public watchlist and update note frontmatter (to-watch).' },
        { id: 'generate-watchlist', name: 'Generate Watchlist', desc: 'Generate a Watchlist.md linking to to-watch notes for the account.' },
        { id: 'generate-favorites', name: 'Generate Favorites', desc: 'Create a Favorites collection from notes marked favorite: true.' },
        { id: 'generate-heatmap', name: 'Generate Watch Heatmap', desc: 'Produce a heatmap visualization under the account Analytics folder.' },
        { id: 'generate-timeline', name: 'Generate Watch Timeline', desc: 'Produce a timeline visualization under the account Analytics folder.' },
        { id: 'generate-charts', name: 'Generate Charts & Statistics', desc: 'Produce charts and statistics (genre/director/actor).' },
        { id: 'generate-rankings', name: 'Generate Top Rankings', desc: 'Generate top directors/actors/genres lists.' },
        { id: 'generate-streak-report', name: 'Generate Streak Report', desc: 'Calculate current and historical watch streaks.' },
        { id: 'organize-by-decade', name: 'Organize Films by Decade', desc: 'Group film notes into decade folders.' },
        { id: 'random-movie-quote', name: 'Random Movie Citation', desc: 'Show a random movie quote from your films.' },
        { id: 'create-film-review', name: 'Create Detailed Film Review', desc: 'Create a review note from a template for the active film note.' },
        { id: 'export-plugin-wiki', name: 'Export Plugin Functions to Wiki', desc: 'Create or update the in-vault Plugin-Functions.md for the active account.' },
    ];

    const overviewTable = ['| Command Palette name | Command ID | Short description |', '| --- | --- | --- |']
        .concat(commands.map(c => `| ${c.name} | ${c.id} | ${c.desc} |`))
        .join('\n');

    const cmdSections = commands.map(c => {
        return [
            `### ${c.name}`,
            `- Command ID: \`${c.id}\``,
            `- Description: ${c.desc}`,
            `- How to run: Command Palette → '${c.name}' or run programmatically using the command id.`,
            '',
            '**Example:**',
            '',
            `Open the Command Palette and type '${c.name}' to execute.`,
            ''
        ].join('\n');
    }).join('\n');

    const parts = [
        `# Plugin Functions — ${accName}`,
        '',
        `_This file is generated by the Letterboxd Mirror plugin. Regenerate anytime using the command: **Export Plugin Functions to Wiki** (Extended)._`,
        '',
        '## Quick start',
        '1. Set your TMDB token in Settings → TMDB integration (optional, improves metadata enrichment).',
        '2. Configure or switch to an active account in Settings → Letterboxd Accounts.',
        '3. Run the command **Sync Active Account** (Command Palette: "Sync Active Account").',
        '4. Generate visual analytics: Command Palette → "Generate Watch Heatmap" / "Generate Watch Timeline".',
        '',
        '## Commands overview',
        '',
        overviewTable,
        '',
        '---',
        '',
        '## Command details',
        '',
        cmdSections,
        '',
        '## Generated files & locations',
        `- Diary / Film notes: ${accName}/ (folder)`,
        `- Analytics: ${analyticsFolder}/ (e.g. ${analyticsFolder}/Heatmap.md, ${analyticsFolder}/Timeline.md)`,
        `- Collections: ${accName}/Collections/`,
        '',
        '## Examples & Workflows',
        "- To update your watchlist and mark notes to-watch:",
        "  1. Open Command Palette → 'Sync Letterboxd Watchlist' (active account must be set)",
        "  2. The plugin will scan your vault for matching film notes and update frontmatter: 'letterboxd_slug', 'status: to-watch' and 'letterboxd_watchlist_owners'.",
        '',
        '- Batch import workflow:',
        "  1. Settings → Batch import films: paste titles, click Import to review items.",
        "  2. The plugin will attempt TMDB enrichment and create film notes in the Films folder.",
        '',
        '## Troubleshooting',
        '- If TMDB token set/remove fails, your Obsidian version may not support vault secrets. The plugin falls back to storing the token in plugin settings (less secure).',
        "- If a command does nothing, ensure an active account is configured in Settings and restart Obsidian after installing/updating the plugin.",
        '',
        '## Changelog',
        `- Plugin version: unknown`,
        `- Last generated: ${now}`,
        '',
        '---',
        '',
        '*This file is safe to regenerate — running Export Plugin Functions to Wiki (Extended) will update or create this note without duplicating content.*',
        ''
    ];

    return parts.join('\n');
}

export async function createOrUpdateWiki(plugin: LetterboxdPlugin, account: LetterboxdAccount): Promise<TFile | null> {
    const rawFolder = (account.name || account.username || account.username || "untitled").trim();
    const safeFolder = rawFolder.replace(/[\\/:*?"<>|]/g, "-");
    const folder = normalizePath(safeFolder);
    const filename = "Plugin-Functions.md";
    const filePath = `${folder}/${filename}`;

    const content = buildWikiMarkdown(account, plugin);

    try {
        try { await plugin.app.vault.createFolder(folder); } catch (e) { /* ignore if exists */ }

        const existing = plugin.app.vault.getAbstractFileByPath(filePath);
        if (existing && (existing as any).path) {
            const file = existing as TFile;
            await plugin.app.vault.modify(file, content);
            new Notice(`Updated plugin wiki: ${filePath}`);
            return file;
        } else {
            const file = await plugin.app.vault.create(filePath, content);
            new Notice(`Created plugin wiki: ${filePath}`);
            return file as TFile;
        }
    } catch (e) {
        console.error('[Letterboxd Plugin] Failed to create/update wiki (extended)', e);
        new Notice('Failed to create or update plugin wiki (extended)');
        return null;
    }
}
